server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/borrowsystem?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    callSettersOnNulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:com/jxd/manage/dao/mapping/*.xml
  type-aliases-package: com.jxd.manage.model 
                        com.jxd.manage.ds
logging:
  level:
    com.jxd.manage.dao: debug
file:
  address: /upload/
  path: upload/**


